// <auto-generated />
using System;
using Cxc.TablasBasicas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace cxc_back.Migrations
{
    [DbContext(typeof(CntContext))]
    [Migration("20210523180730_CodigosCiiu")]
    partial class CodigosCiiu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cxc.TablasBasicas.Models.CntBancos", b =>
                {
                    b.Property<int>("BancoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BancoLongitud")
                        .HasColumnType("int");

                    b.Property<string>("BancoNombre")
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.Property<DateTime?>("Fecha_Computador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("Fecha_Impresion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Reimpresion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fuente")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("CP3121");

                    b.Property<string>("FuenteImport")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("Proceso")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValueSql("CURRENT_USER");

                    b.HasKey("BancoId");

                    b.ToTable("Bancos", "CNT");
                });

            modelBuilder.Entity("Cxc.TablasBasicas.Models.CntCodigosCiiu", b =>
                {
                    b.Property<string>("CodigoCiiuId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<bool>("CodigoCiiuBloqueo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoCiiuDescripcion")
                        .HasMaxLength(246)
                        .HasColumnType("nvarchar(246)");

                    b.Property<bool>("CodigoCiiuclase")
                        .HasColumnType("bit");

                    b.Property<bool>("CodigoCiiudivision")
                        .HasColumnType("bit");

                    b.Property<bool>("CodigoCiiugrupo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Fecha_Computador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("Fecha_Impresion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Reimpresion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fuente")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("CP3000");

                    b.Property<string>("FuenteImport")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("Proceso")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValueSql("CURRENT_USER");

                    b.HasKey("CodigoCiiuId");

                    b.ToTable("CodigosCiiu", "CNT");
                });
#pragma warning restore 612, 618
        }
    }
}
